### ISSUE TITLE
recompile calpost for the calculation of greater ranks than 10

### ISSUE THREAD

**Issue by maxbre** [gauss-ma/calpuff#3]
hello

my compliments for your excellent work about recompiling CALPUFF modeling system under Linux

consider that "native" CALPOST model cannot accept a maximum rank greater than 10 (MXRNK <=10) I would like to recompile the source code to allow for the calculation also of higher ranks (sometimes that is needed for the evaluation of some air quality standards)

I think to understand that the above limitation is set in the file "params.pst" at line 23

`      PARAMETER(mxrnk=10,mxtop=4)             !Keep mxtop=4
`

do you have any experience about that? 
do you know how to properly recompile the CALPOST source code for that?

I've been trying to change the above line of the file by setting mxrnk=500, but without much success

thanks

**Comment by ramespada** [comment]
Ciao Massimo, grazie mille per il tuo cumplimenti! 

Try to add the following flag to the FCFLAGS  variables (inside the config.var file)
-mcmodel=large

so you will have:

FCFLAGS=-c -O2 -static -std=legacy -mtune=native -fbacktrace -fcheck=bounds **-mcmodel=large**

and then recompile it

If you have any problem please write me back and I will try to help you. Don't forget to add the errors that you get so I have some hints about what is wrong

Regards!

**Comment by maxbre** [comment]
Hola Rama, es un placer conocerte!

I'm right now switching to English because my written Spanish is quite poor: I can somehow understand the spoken language... ma si hablas despacio!

I followed your instructions and the recompilation of the source code apparently went fine, with no errors

This is what I did:

makefile
#----------------
#Compiler and library flags:
`FCFLAGS=-c -O2 -static -std=legacy -mtune=native -fbacktrace -fcheck=bounds -mcmodel=large`

params.pst, line 23
#----------------
`      PARAMETER(mxrnk=500,mxtop=4)             !Keep mxtop=4`

paramsl.pst, line 23      
#----------------
`      PARAMETER(mxrnk=500,mxtop=4)             !Keep mxtop=4`
      
paramsm.pst, line 23      
#----------------
`      PARAMETER(mxrnk=500,mxtop=4)             !Keep mxtop=4`

paramss.pst, line 22      
#----------------
`      PARAMETER(mxrnk=500,mxtop=4)             !Keep mxtop=4`
      

but when I'm running calpost with my one my sample data I get the following:     
      
FATAL ERRORS were found in CALPOST.INP!
 Review the messages written to the list-file.
 
 calpost.lst
 **************    FATAL    ***************
 Rank exceeds allocated area!
   NRNK, MXRNK =         400          10
   Increase parameter MXRNK in PARAMS.PST, or
   decrease largest value entered in itop array

there must be something to change somewhere else in the original source code of calpost
thanks anyway for your help

Adiós, que tengas un lindo día.

**Comment by ramespada** [comment]
Hi Massi!

Sorry for my late response, I have been busy working on another project.

It seems that somewhere in the code mxrnk is set to 10, but I couldn't found where. mxrnk is only set in the *.pst files, and as you told me you changed those values to 500.

My only guess is that maybe the executable still the old one. Could you make sure to delete it and try to recompile it to see if it works?

Cheers!

**Comment by maxbre** [comment]
I can see the variable 'mxrnk' is somehow initialised through: "data NRNKV24/22/" as in row 1887 of "calpost.for" file, but I do not exactly understand how it works and how to accomplish the desired result...

still searching

hola

**Comment by ramespada** [comment]
Hi!

As far as I know, "data NRNKV24/22/" is just another way to assign a value (in this case 22) to the variable NRNKV24.  

So, then i found that NRNKV24 is passed to NRNK variable (lines 11984 and 12105 on calpost.for), but has not influence on MXRNK who is supposed to be wrong. Furthermore i dont found any other place where MXRNK is modiffied other than the .pst files that you have modified..

So far, no clues... :(

Would it be possible to share your inputs files with me so I can test them?
